### ISSUE TITLE
Travis CI fails

### ISSUE THREAD

**Issue by hackrid** [openxc/isotp-c#3]
https://travis-ci.org/hackrid/isotp-c/builds/142710775

**Comment by peplin** [comment]
Hey there! You have this commit in your tree that broke it: https://github.com/hackrid/isotp-c/commit/901370aa72d39aaab2a7a7eec1c8d4b4b7b41aa5

This isn't in master, so you may have forked from someone else's repo? I just added a small update to the main repository at the tests are passing.
