### ISSUE TITLE
no such file #include <bitfield/bitfield.h>

### ISSUE THREAD

**Issue by snikeguo** [openxc/isotp-c#6]
no such file #include <bitfield/bitfield.h>

**Comment by emarsman** [comment]
Please provide more information. What commands did you run? 

I'm assuming you didn't update the git submodules. bitfield is in /deps/. 

I will close unless you can provide enough information for me to reproduce the error. 

Regards,
Eric

**Comment by snikeguo** [comment]
thx, i  find it
